stages:
  - build
  - deploy
  - promote

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: "tcp://docker:2375"
  IMAGE_NAME: andrianey/rama-wedding
  DOCKER_BUILDKIT: "1"
  PRISMA_CLI_BINARY_TARGETS: "native,linux-musl-openssl-3.0.x,linux-musl-arm64-openssl-3.0.x"
  TARGET_TAG:
    value: "latest"
    description: "Tag to promote the staging build to (usually latest)"

# ─── JOB 1: Build & Push (Tagged as -staging) ────────────────────────────────

build:
  stage: build
  tags:
    - oracle
  image: docker:24-cli
  services:
    - name: docker:24-dind
  before_script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
    - docker run --privileged --rm tonistiigi/binfmt --install all
    - docker buildx create --use --name mybuilder
  script:
    - |
      docker buildx build \
        --platform linux/arm64,linux/amd64 \
        --build-arg NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=dsfz9c2hm \
        --build-arg NEXT_PUBLIC_USE_CLOUDINARY=true \
        --provenance=false \
        --cache-from type=registry,ref=$IMAGE_NAME:cache \
        --cache-to type=registry,ref=$IMAGE_NAME:cache,mode=max \
        -t $IMAGE_NAME:staging \
        -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA \
        --push .
  only:
    - main
    - master

promote:
  stage: promote
  tags:
    - oracle
  image: docker:24-cli
  services:
    - name: docker:24-dind
  before_script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
    - docker buildx create --use --name mybuilder
  script:
    - |
      docker buildx imagetools create \
        -t $IMAGE_NAME:$TARGET_TAG \
        $IMAGE_NAME:staging
    - |
      TOKEN=$(curl -s \
        -H "Content-Type: application/json" \
        -X POST \
        -d "{\"username\": \"${DOCKER_HUB_USERNAME}\", \"password\": \"${DOCKER_HUB_PASSWORD}\"}" \
        https://hub.docker.com/v2/users/login/ | jq -r .token)
      curl -i -X DELETE \
        -H "Authorization: JWT ${TOKEN}" \
        "https://hub.docker.com/v2/repositories/andrianey/rama-wedding/tags/staging"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: manual
    - when: never